version: "3.3"

volumes:
  grafana-data:
  prometheus-data:    

services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.2.2
    container_name: slave_node_exporter
    command:
    - '--path.rootfs=/host'
    restart: unless-stopped
    pid: host
    expose:
    - 9100
    volumes:
    - '/:/host:ro,rslave'

  prometheus:
    image: prom/prometheus:latest
    container_name: master_prometheus
    restart: unless-stopped
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - prometheus-data:/prometheus
    ports:
    - 9090:9090
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    - '--storage.tsdb.retention.time=10m'
    - '--storage.tsdb.retention.size=10GB'
    - '--web.enable-lifecycle'
    - '--web.enable-admin-api'

  cadvisor:
    image: zcube/cadvisor:latest
    container_name: slave_cAdvisor
    restart: unless-stopped
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /dev/disk/:/dev/disk:ro