version: '3.8'
services:
  superlink:
    image: flwr/superlink:1.18.0
    container_name: superlink
    ports:
    - 9091:9091
    - 9092:9092
    - 9093:9093
    networks:
    - master_default
    command:
    - --insecure
    - --isolation
    - process
    cpuset: '8'
    mem_limit: 2g
  serverapp:
    build:
      context: ..
      dockerfile: dockerfiles/serverapp.Dockerfile
    container_name: serverapp
    networks:
    - master_default
    command:
    - --insecure
    - --serverappio-api-address
    - superlink:9091
    depends_on:
    - superlink
    volumes:
    - ../local-execution/results:/app/results/local-execution:rw
    - ../projectconf.toml:/app/projectconf.toml:rw
    cpuset: '9'
    mem_limit: 2g
  supernode-1:
    image: flwr/supernode:1.18.0
    container_name: supernode-1
    ports:
    - 9094:9094
    networks:
    - master_default
    command:
    - --insecure
    - --superlink
    - superlink:9092
    - --node-config
    - partition-id=0 num-partitions=8 partition-type="iid" dataset-name="uoft-cs/cifar10"
    - --clientappio-api-address
    - 0.0.0.0:9094
    - --isolation
    - process
    depends_on:
    - superlink
    environment:
    - DEVICE=supernode-1
    cpuset: '0'
    mem_limit: 1g
  client-1:
    build:
      context: ..
      dockerfile: dockerfiles/clientapp.Dockerfile
    container_name: client-1
    networks:
    - master_default
    command:
    - --insecure
    - --clientappio-api-address
    - supernode-1:9094
    depends_on:
    - supernode-1
    environment:
    - DEVICE=supernode-1
    mem_limit: 2g
    cpuset: '10'
    cpus: 1
  supernode-2:
    image: flwr/supernode:1.18.0
    container_name: supernode-2
    ports:
    - 9095:9095
    networks:
    - master_default
    command:
    - --insecure
    - --superlink
    - superlink:9092
    - --node-config
    - partition-id=1 num-partitions=8 partition-type="iid" dataset-name="uoft-cs/cifar10"
    - --clientappio-api-address
    - 0.0.0.0:9095
    - --isolation
    - process
    depends_on:
    - superlink
    environment:
    - DEVICE=supernode-2
    cpuset: '1'
    mem_limit: 1g
  client-2:
    build:
      context: ..
      dockerfile: dockerfiles/clientapp.Dockerfile
    container_name: client-2
    networks:
    - master_default
    command:
    - --insecure
    - --clientappio-api-address
    - supernode-2:9095
    depends_on:
    - supernode-2
    environment:
    - DEVICE=supernode-2
    mem_limit: 2g
    cpuset: '11'
    cpus: 1
  supernode-3:
    image: flwr/supernode:1.18.0
    container_name: supernode-3
    ports:
    - 9096:9096
    networks:
    - master_default
    command:
    - --insecure
    - --superlink
    - superlink:9092
    - --node-config
    - partition-id=2 num-partitions=8 partition-type="iid" dataset-name="uoft-cs/cifar10"
    - --clientappio-api-address
    - 0.0.0.0:9096
    - --isolation
    - process
    depends_on:
    - superlink
    environment:
    - DEVICE=supernode-3
    cpuset: '2'
    mem_limit: 1g
  client-3:
    build:
      context: ..
      dockerfile: dockerfiles/clientapp.Dockerfile
    container_name: client-3
    networks:
    - master_default
    command:
    - --insecure
    - --clientappio-api-address
    - supernode-3:9096
    depends_on:
    - supernode-3
    environment:
    - DEVICE=supernode-3
    mem_limit: 2g
    cpuset: '12'
    cpus: 1
  supernode-4:
    image: flwr/supernode:1.18.0
    container_name: supernode-4
    ports:
    - 9097:9097
    networks:
    - master_default
    command:
    - --insecure
    - --superlink
    - superlink:9092
    - --node-config
    - partition-id=3 num-partitions=8 partition-type="iid" dataset-name="uoft-cs/cifar10"
    - --clientappio-api-address
    - 0.0.0.0:9097
    - --isolation
    - process
    depends_on:
    - superlink
    environment:
    - DEVICE=supernode-4
    cpuset: '3'
    mem_limit: 1g
  client-4:
    build:
      context: ..
      dockerfile: dockerfiles/clientapp.Dockerfile
    container_name: client-4
    networks:
    - master_default
    command:
    - --insecure
    - --clientappio-api-address
    - supernode-4:9097
    depends_on:
    - supernode-4
    environment:
    - DEVICE=supernode-4
    mem_limit: 2g
    cpuset: '13'
    cpus: 1
  supernode-5:
    image: flwr/supernode:1.18.0
    container_name: supernode-5
    ports:
    - 9098:9098
    networks:
    - master_default
    command:
    - --insecure
    - --superlink
    - superlink:9092
    - --node-config
    - partition-id=4 num-partitions=8 partition-type="iid" dataset-name="uoft-cs/cifar10"
    - --clientappio-api-address
    - 0.0.0.0:9098
    - --isolation
    - process
    depends_on:
    - superlink
    environment:
    - DEVICE=supernode-5
    cpuset: '4'
    mem_limit: 1g
  client-5:
    build:
      context: ..
      dockerfile: dockerfiles/clientapp.Dockerfile
    container_name: client-5
    networks:
    - master_default
    command:
    - --insecure
    - --clientappio-api-address
    - supernode-5:9098
    depends_on:
    - supernode-5
    environment:
    - DEVICE=supernode-5
    mem_limit: 2g
    cpuset: '14'
    cpus: 1
  supernode-6:
    image: flwr/supernode:1.18.0
    container_name: supernode-6
    ports:
    - 9099:9099
    networks:
    - master_default
    command:
    - --insecure
    - --superlink
    - superlink:9092
    - --node-config
    - partition-id=5 num-partitions=8 partition-type="iid" dataset-name="uoft-cs/cifar10"
    - --clientappio-api-address
    - 0.0.0.0:9099
    - --isolation
    - process
    depends_on:
    - superlink
    environment:
    - DEVICE=supernode-6
    cpuset: '5'
    mem_limit: 1g
  client-6:
    build:
      context: ..
      dockerfile: dockerfiles/clientapp.Dockerfile
    container_name: client-6
    networks:
    - master_default
    command:
    - --insecure
    - --clientappio-api-address
    - supernode-6:9099
    depends_on:
    - supernode-6
    environment:
    - DEVICE=supernode-6
    mem_limit: 2g
    cpuset: '15'
    cpus: 1
  supernode-7:
    image: flwr/supernode:1.18.0
    container_name: supernode-7
    ports:
    - 9100:9100
    networks:
    - master_default
    command:
    - --insecure
    - --superlink
    - superlink:9092
    - --node-config
    - partition-id=6 num-partitions=8 partition-type="iid" dataset-name="uoft-cs/cifar10"
    - --clientappio-api-address
    - 0.0.0.0:9100
    - --isolation
    - process
    depends_on:
    - superlink
    environment:
    - DEVICE=supernode-7
    cpuset: '6'
    mem_limit: 1g
  client-7:
    build:
      context: ..
      dockerfile: dockerfiles/clientapp.Dockerfile
    container_name: client-7
    networks:
    - master_default
    command:
    - --insecure
    - --clientappio-api-address
    - supernode-7:9100
    depends_on:
    - supernode-7
    environment:
    - DEVICE=supernode-7
    mem_limit: 2g
    cpuset: '16'
    cpus: 1
  supernode-8:
    image: flwr/supernode:1.18.0
    container_name: supernode-8
    ports:
    - 9101:9101
    networks:
    - master_default
    command:
    - --insecure
    - --superlink
    - superlink:9092
    - --node-config
    - partition-id=7 num-partitions=8 partition-type="iid" dataset-name="uoft-cs/cifar10"
    - --clientappio-api-address
    - 0.0.0.0:9101
    - --isolation
    - process
    depends_on:
    - superlink
    environment:
    - DEVICE=supernode-8
    cpuset: '7'
    mem_limit: 1g
  client-8:
    build:
      context: ..
      dockerfile: dockerfiles/clientapp.Dockerfile
    container_name: client-8
    networks:
    - master_default
    command:
    - --insecure
    - --clientappio-api-address
    - supernode-8:9101
    depends_on:
    - supernode-8
    environment:
    - DEVICE=supernode-8
    mem_limit: 2g
    cpuset: '17'
    cpus: 1
networks:
  master_default:
    external: true
